### ISSUE TITLE
PDF name to JPG name

### ISSUE THREAD

**Issue by marlouis** [cage1016/alfred-pdf2image#1]
Dear cage1016, 

thank you so much for your workflow. I was wondering if it would possible to rename the jpg exported file with the same exact name as the original PDF file. 

I guess changing the code line would be the thing to do, I usually convert all the pages at once and don't need the {var:file} page "{var:page]" extension. 

Regards :)

**Comment by cage1016** [comment]
Hi, @marlouis 

Due to `pdf2image` is designed to convert pdf to image for multiple range at the same time. Could you give me a example?

**Comment by marlouis** [comment]
Hi @cage1016 and thanks for your response. 

Sure, it may be not the initial purpose of the app but I'd like to convert the PDF into an image without modifying the filename such as : 

![S1](https://github.com/cage1016/alfred-pdf2image/assets/62121383/7a49c032-6c53-40ec-85ce-46e8bb7d283d)
![S2](https://github.com/cage1016/alfred-pdf2image/assets/62121383/3dd223c4-5d04-48c0-8f98-3c4a315aa16f)
![S3](https://github.com/cage1016/alfred-pdf2image/assets/62121383/52b06f6f-5d6b-4c7b-a6d7-7116b8bb7cbd)

**Comment by cage1016** [comment]
Hi, @marlouis 

The PDF file seems to be ONLY ONE page as your screenshot show above, right? 

Assumed we have **ONE** page PDF called test.pdf

## Current scenario

test.pdf → test-part1-001.png

## Scenario you need

test.pdf → test.png

Please correct me if any missing understanding

**Comment by marlouis** [comment]
Hi :) 

That's correct : 

Current scenario
test.pdf → test-part1-001.png

Scenario I need
test.pdf → test.png

**Comment by cage1016** [comment]
Hi, @marlouis 

Please update [Release v0.2.0 · cage1016/alfred-pdf2image](https://github.com/cage1016/alfred-pdf2image/releases/tag/v0.2.0)

v0.2.0 - Add a single page document, save the image as the same filename as the pdf

You could custom workflow a little bit to fulfill your requirement 

1. Add new file action
![CleanShot 2023-07-25 at 00 14 35@2x](https://github.com/cage1016/alfred-pdf2image/assets/678607/38a7ee25-696c-4ea4-b792-bd8ef5e4b98f)

2. Add argument `1` -> Page 1
![CleanShot 2023-07-25 at 00 14 55@2x](https://github.com/cage1016/alfred-pdf2image/assets/678607/3b435d70-dd70-4fa0-a696-c484221068c3)

3.  Link new file action (One page scenario) to `alfred-pdf2image`
![CleanShot 2023-07-25 at 00 15 11@2x](https://github.com/cage1016/alfred-pdf2image/assets/678607/d0652e8d-4f87-412b-a2a6-98ddd54d6b59)

4.  Launch custom file action
![CleanShot 2023-07-25 at 00 15 36@2x](https://github.com/cage1016/alfred-pdf2image/assets/678607/6bc36923-3ad1-4698-8972-a1e4e9c5b4d4)

5.  save the image as the same filename as the pdf
![CleanShot 2023-07-25 at 00 21 21@2x](https://github.com/cage1016/alfred-pdf2image/assets/678607/992c2c9f-4b3d-4613-8b81-75ae92abd868)

** New update ONLY occurs at single page PDF file **

**Comment by marlouis** [comment]
Dear Cage1016, 

Works as I intended, thank you so much !
Have a great day :)
